---
flags:
  - id: 'TIME004'
    description: 'Time diff when executing git clone command in Dockerfile.'
    filepath: '.*'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: '\d+ \+\d{4}\tclone:'
    severity: 'Low'
    metadata: True

  - id: 'TIME005'
    description: "Files in zip have different time stamp."
    filepath: '.*'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: 'bx stor \d{2}-[A-Za-z]{3}-\d{2} \d{2}:\d{2}'
    severity: 'Low'
    metadata: True

  - id: 'TIME006'
    description: "Time difference in different format that starts with 1714"
    filepath: '.*'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: '\b1714\d*\b'
    severity: 'Low'
    metadata: True

  - id: 'TIME007'
    description: "File listing time difference in different format."
    filepath: '.*'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: '\b\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{6}\b'
    severity: 'Low'
    metadata: True

  - id: 'TIME008'
    description: "Logging time difference."
    filepath: '.*'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: '\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}'
    severity: 'Low'
    metadata: True

  - id: 'TIME009'
    description: "Date and time difference for Go Build"
    filepath: '.*'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: '(Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s([0-2]?[0-9]|3[01])\s([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])\sUTC\s[0-9]{4}'
    severity: 'Low'
    metadata: True

  - id: 'TIME010'
    description: "Date and time difference for Go binary output"
    filepath: '.*'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: '(Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s([0-2]?[0-9]|3[01])\s([01][0-9]|2[0-3]):([0-5][0-9])'
    severity: 'Low'
    metadata: True

  - id: 'TIME011'
    description: 'Modified time in git index file'
    filepath: '.*/\.git/index'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: 'Modified:\s*\d+[.]\d+'
    severity: 'Low'
    metadata: True

  - id: 'TIME012'
    description: "Modified file time"
    filepath: '.*'
    filetype: '.*'
    command: 'stat {}'
    comment: '.*'
    indiff: 'Modify:\s.*'
    severity: 'Low'
    metadata: True

  - id: 'TIME013'
    description: 'Created time in git index file'
    filepath: '.*/\.git/index'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: 'Created:\s*\d+[.]\d+'
    severity: 'Low'
    metadata: True

  - id: 'TIME014'
    description: "Keybox created time diff"
    filepath: '.*'
    filetype: '.*'
    command: 'kbxutil'
    comment: '.*'
    indiff: '(?i)created-at:\s(\d+)'
    severity: 'Low'
    metadata: True

  - id: 'TIME015'
    description: "Keybox last maintained time diff"
    filepath: '.*'
    filetype: '.*'
    command: 'kbxutil'
    comment: '.*'
    indiff: 'last-maint:\s(\d+)'
    severity: 'Low'
    metadata: True

  - id: 'TIME016'
    description: "Python bytecode moddate differences "
    filepath: '.*'
    filetype: '.*'
    command: 'Python bytecode'
    comment: '.*'
    indiff: 'moddate:.*'
    severity: 'Low'
    metadata: True

  - id: 'TIME017'
    description: "Python last check time difference"
    filepath: '.*'
    filetype: '.*'
    command: 'Pretty-printed'
    comment: '.*'
    indiff: '\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?[+-]\d{2}:\d{2}'
    severity: 'Low'
    metadata: True

  - id: 'TIME018'
    description: "Time difference in unpacked db"
    filepath: '.*\.log'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: '\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\+\d{4}'
    severity: 'Low'
    metadata: True

  - id: 'TIME019'
    description: "Timer setup time differences"
    filepath: '.*var/log/dnf.log'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: '\d+\sms'
    severity: 'Low'
    metadata: True

  - id: 'PLAT004'
    description: 'Different device ID field in git index file'
    filepath: '.*/\.git\/index'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: 'Device ID:\s*\(\d, \d+\)'
    severity: 'Medium'
    metadata: True

  - id: 'CACHE007'
    description: 'ldconfig aux-cache'
    filepath: 'rootfs/var/cache/ldconfig/aux-cache'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: '.*'
    severity: 'Low'
    metadata: False

  - id: 'CACHE008'
    description: 'Go-build cache'
    filepath: '\.cache/go-build/'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: '.*'
    severity: 'Low'
    metadata: False

  - id: 'CACHE009'
    description: 'Go Module Download Cache'
    filepath: '/go/pkg/mod/cache/download/'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: '.*'
    severity: 'Low'
    metadata: False

  - id: 'CACHE010'
    description: 'Pip cache files'
    filepath: '\.cache/pip/'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: '.*'
    severity: 'Low'
    metadata: True

  - id: 'CACHE011'
    description: 'Compiled Python (.pyc) differences'
    filepath: '\.pyc$'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: '.*'
    severity: 'Low'
    metadata: False

  - id: 'RNG002'
    description: 'Inode differences in Git index files'
    filepath: '.*/\.git/index'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: 'Inode:\s*\d+'
    severity: 'Low'
    metadata: False

  - id: 'RNG003'
    description: "Difference in sqlite3 transaction ids"
    filepath: '.*'
    filetype: '.*'
    command: 'sqlite3 {} .dump'
    comment: '.*'
    indiff: '\b\d,\d+,\d+\b'
    severity: 'Medium'
    metadata: False

  - id: 'RNG004'
    description: 'uuid differences in fontconfig cache filenames'
    filepath: '.*'
    filetype: '.*'
    command: 'file list'
    comment: '.*'
    indiff: '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}'
    severity: 'Medium'
    metadata: False

  - id: 'RNG005'
    description: '/etc/shadow last password change difference'
    filepath: '.*/etc/shadow'
    filetype: '.*'
    command: '.*'
    comment: '.*'
    indiff: '^[a-zA-Z0-9_-]+:[!]+:[0-9]+:(?:[0-9]*:)*$'
    severity: 'Medium'
    metadata: False

  - id: 'RNG006'
    description: 'Generated certificate differences'
    filepath: '.*\.(pem|crt)'
    filetype: ''
    command: '.*'
    comment: '.*'
    indiff: '.*'
    severity: 'Medium'
    metadata: False
