---
flags:
  #  - id: 'TIME002'
  #    description: 'A timestamp diff caused when files are modified at different times.'
  #    filepath: '.'
  #    filetype: '.'
  #    command: 'stat {}'
  #    comment: '.'
  #    indiff: 'Modify: [0-9]{1,4}-[0-9]{1,2}-[0-9]{1,2}[ ]+[0-9]{1,2}\:[0-9]{1,2}\:[0-9]{1,2}(\.[0-9]+)?'
    
  - id: 'TIME004'
    description: 'Time diff when executing git clone command in Dockerfile.'
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '\d+ \+\d{4}\tclone:'

  - id: 'TIME005'
    description: "Files in zip have different time stamp."
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: 'bx stor \d{2}-[A-Za-z]{3}-\d{2} \d{2}:\d{2}'

  - id: 'TIME006'
    description: "Time difference in different format that starts with 1714"
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '\b1714\d*\b'

  - id: 'TIME007'
    description: "File listing time difference in different format."
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '\b\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{6}\b'

  - id: 'TIME008'
    description: "Logging time difference."
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}'

  - id: 'TIME009'
    description: "Date and time difference for Go Build"
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '(Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s([0-2]?[0-9]|3[01])\s([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])\sUTC\s[0-9]{4}'

  - id: 'TIME010'
    description: "Date and time difference for Go binary output"
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '(Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s([0-2]?[0-9]|3[01])\s([01][0-9]|2[0-3]):([0-5][0-9])'

  - id: 'TIME011'
    description: "Modified and build time in different format"
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '1719\d*'

  - id: 'TIME012'
    description: "Modified time diff (Unix timestamp)"
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: 'Modify:\s.*'

  - id: 'TIME013'
    description: "Modified time diff (ISO 8601 Datetime)"
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: 'Modify:\s\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'

  - id: 'TIME014'
    description: "Keybox created time diff"
    filepath: '.'
    filetype: '.'
    command: 'kbxutil'
    comment: '.'
    indiff: '(?i)created-at:\s(\d+)'

  - id: 'TIME015'
    description: "Keybox last maintained time diff"
    filepath: '.'
    filetype: '.'
    command: 'kbxutil'
    comment: '.'
    indiff: 'last-maint:\s(\d+)'

  - id: 'TIME016'
    description: "Moddate differences "
    filepath: '.'
    filetype: '.'
    command: 'Python bytecode'
    comment: '.'
    indiff: 'x[0-9a-fA-F]+'

  - id: 'TIME017'
    description: "Mod date differences related to cache file list difference"
    filepath: '.'
    filetype: '.'
    command: 'file list'
    comment: '.'
    indiff: '([0-9a-fA-F\-]+)-le64\.cache-7'

  - id: 'TIME018'
    description: "Python last check time difference"
    filepath: '.'
    filetype: '.'
    command: 'Pretty-printed'
    comment: '.'
    indiff: '\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?[+-]\d{2}:\d{2}'

  - id: 'TIME019'
    description: "Time difference in unpaceked db"
    filepath: '.*\.log'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\+\d{4}'

  - id: 'EXT-transaction-id'
    description: "Difference in transaction id"
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '\b\d,\d+,\d+\b'

  - id: 'TIME-debug-timer'
    description: "Timer setup time differences"
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '\d+\sms'

  - id: 'EXT-checksum'
    description: "Keybox Checksum difference"
    filepath: '.*\.kbx'
    filetype: '.'
    command: 'kbxutil'
    comment: '.'
    indiff: 'Checksum:\s([a-zA-Z0-9]+)'

  - id: 'PLAT-inode'
    description: 'Inode diff when we are installing tars in Dockerfile.'
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: 'Inode:\s*\d+'

  - id: 'EXT-packhash'
    description: '.Pack hash difference, cause is unknown'
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: 'pack-[a-fA-F0-9]+\.pack'

  - id: 'PLAT-gnu-offset'
    description: 'GNU related compilation difference'
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '\(strp\) \(offset: 0x[0-9a-fA-F]+\)'

  - id: 'PLAT-size'
    description: 'Build size difference in multiple kinds of build'
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: 'Size: \d+'

  - id: 'PLAT-blocks'
    description: 'Block size difference in multiple kinds of build'
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '\tBlocks:\s*\d+'

  - id: 'EXT-git-index-created'
    description: 'Created git index'
    filepath: '.*/\.git/index'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: 'Created:\s*\d+[.]\d+'

  - id: 'EXT-git-index-modified'
    description: 'Modified git index'
    filepath: '.*/\.git/index'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: 'Modified:\s*\d+[.]\d+'

  - id: 'PLAT-git-index-device'
    description: 'Device ID field in git index'
    filepath: '.*/\.git\/index'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: 'Device ID:\s*\(\d, \d+\)'

  - id: 'EXT-cert-pem'
    description: 'Generated certificate differences'
    filepath: '.*\.pem'
    filetype: ''
    command: '.'
    comment: '.'
    indiff: '.'

  - id: 'EXT-cert-crt'
    description: 'Generated certificate differences'
    filepath: '.*\.crt'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '.'

  - id: 'CACHE-go-build'
    description: 'Go-build cache'
    filepath: '\.cache/go-build/'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '.'

  - id: 'CACHE-go-mod'
    description: 'Go Module Download Cache'
    filepath: '/go/pkg/mod/cache/download/'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '.'

  - id: 'CACHE-pip'
    description: 'Pip cache files'
    filepath: '\.cache/pip/'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '.'

  - id: 'EXT-elf-gopclntab'
    description: 'Golang binary Program Counter Line Table differences'
    filepath: '.'
    filetype: '.'
    command: 'readelf --wide --decompress --hex-dump=.gopclntab {}'
    comment: '.'
    indiff: '.'

  - id: 'EXT-pyc-format'
    description: 'Compiled Python (.pyc) format differences'
    filepath: '\.pyc$'
    filetype: '.'
    command: '.'
    comment: 'but no file-specific differences were detected'
    indiff: '.'

  - id: 'EXT-pyc'
    description: 'Compiled Python (.pyc) differences'
    filepath: '\.pyc$'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '.'

  - id: 'CACHE-cache'
    description: 'ldconfig aux-cache'
    filepath: 'rootfs/var/cache/ldconfig/aux-cache'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '.'

  - id: 'RNG-uuid'
    description: 'uuid differences when listing cache file.'
    filepath: '.'
    filetype: '.'
    command: 'file list'
    comment: '.'
    indiff: '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}'
  
  - id: 'PLAT-stat'
    description: 'stat{} command returns results that usually differ by 1 in digit.'
    filepath: '.'
    filetype: '.'
    command: '.'
    comment: '.'
    indiff: '^[a-zA-Z0-9_-]+:[!]+:[0-9]+:(?:[0-9]*:)*$'
    